//go:build !ignore_autogenerated

/*
Copyright 2025 Guided Traffic GmbH.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonStatus) DeepCopyInto(out *CommonStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonStatus.
func (in *CommonStatus) DeepCopy() *CommonStatus {
	if in == nil {
		return nil
	}
	out := new(CommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexAtlassianCrowdConnector) DeepCopyInto(out *DexAtlassianCrowdConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexAtlassianCrowdConnector.
func (in *DexAtlassianCrowdConnector) DeepCopy() *DexAtlassianCrowdConnector {
	if in == nil {
		return nil
	}
	out := new(DexAtlassianCrowdConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexAtlassianCrowdConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexAtlassianCrowdConnectorList) DeepCopyInto(out *DexAtlassianCrowdConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexAtlassianCrowdConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexAtlassianCrowdConnectorList.
func (in *DexAtlassianCrowdConnectorList) DeepCopy() *DexAtlassianCrowdConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexAtlassianCrowdConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexAtlassianCrowdConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexAtlassianCrowdConnectorSpec) DeepCopyInto(out *DexAtlassianCrowdConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdminPasswordRef != nil {
		in, out := &in.AdminPasswordRef, &out.AdminPasswordRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexAtlassianCrowdConnectorSpec.
func (in *DexAtlassianCrowdConnectorSpec) DeepCopy() *DexAtlassianCrowdConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexAtlassianCrowdConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexAtlassianCrowdConnectorStatus) DeepCopyInto(out *DexAtlassianCrowdConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexAtlassianCrowdConnectorStatus.
func (in *DexAtlassianCrowdConnectorStatus) DeepCopy() *DexAtlassianCrowdConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexAtlassianCrowdConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexAuthProxyConnector) DeepCopyInto(out *DexAuthProxyConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexAuthProxyConnector.
func (in *DexAuthProxyConnector) DeepCopy() *DexAuthProxyConnector {
	if in == nil {
		return nil
	}
	out := new(DexAuthProxyConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexAuthProxyConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexAuthProxyConnectorList) DeepCopyInto(out *DexAuthProxyConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexAuthProxyConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexAuthProxyConnectorList.
func (in *DexAuthProxyConnectorList) DeepCopy() *DexAuthProxyConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexAuthProxyConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexAuthProxyConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexAuthProxyConnectorSpec) DeepCopyInto(out *DexAuthProxyConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexAuthProxyConnectorSpec.
func (in *DexAuthProxyConnectorSpec) DeepCopy() *DexAuthProxyConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexAuthProxyConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexAuthProxyConnectorStatus) DeepCopyInto(out *DexAuthProxyConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexAuthProxyConnectorStatus.
func (in *DexAuthProxyConnectorStatus) DeepCopy() *DexAuthProxyConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexAuthProxyConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexBitbucketConnector) DeepCopyInto(out *DexBitbucketConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexBitbucketConnector.
func (in *DexBitbucketConnector) DeepCopy() *DexBitbucketConnector {
	if in == nil {
		return nil
	}
	out := new(DexBitbucketConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexBitbucketConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexBitbucketConnectorList) DeepCopyInto(out *DexBitbucketConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexBitbucketConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexBitbucketConnectorList.
func (in *DexBitbucketConnectorList) DeepCopy() *DexBitbucketConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexBitbucketConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexBitbucketConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexBitbucketConnectorSpec) DeepCopyInto(out *DexBitbucketConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexBitbucketConnectorSpec.
func (in *DexBitbucketConnectorSpec) DeepCopy() *DexBitbucketConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexBitbucketConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexBitbucketConnectorStatus) DeepCopyInto(out *DexBitbucketConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexBitbucketConnectorStatus.
func (in *DexBitbucketConnectorStatus) DeepCopy() *DexBitbucketConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexBitbucketConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexCORSSpec) DeepCopyInto(out *DexCORSSpec) {
	*out = *in
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexCORSSpec.
func (in *DexCORSSpec) DeepCopy() *DexCORSSpec {
	if in == nil {
		return nil
	}
	out := new(DexCORSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexEtcdSSLSpec) DeepCopyInto(out *DexEtcdSSLSpec) {
	*out = *in
	if in.CARef != nil {
		in, out := &in.CARef, &out.CARef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.CertRef != nil {
		in, out := &in.CertRef, &out.CertRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.KeyRef != nil {
		in, out := &in.KeyRef, &out.KeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexEtcdSSLSpec.
func (in *DexEtcdSSLSpec) DeepCopy() *DexEtcdSSLSpec {
	if in == nil {
		return nil
	}
	out := new(DexEtcdSSLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexEtcdStorageSpec) DeepCopyInto(out *DexEtcdStorageSpec) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(DexEtcdSSLSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexEtcdStorageSpec.
func (in *DexEtcdStorageSpec) DeepCopy() *DexEtcdStorageSpec {
	if in == nil {
		return nil
	}
	out := new(DexEtcdStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexExpirySpec) DeepCopyInto(out *DexExpirySpec) {
	*out = *in
	if in.RefreshTokens != nil {
		in, out := &in.RefreshTokens, &out.RefreshTokens
		*out = new(DexRefreshTokenExpirySpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexExpirySpec.
func (in *DexExpirySpec) DeepCopy() *DexExpirySpec {
	if in == nil {
		return nil
	}
	out := new(DexExpirySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGRPCSpec) DeepCopyInto(out *DexGRPCSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGRPCSpec.
func (in *DexGRPCSpec) DeepCopy() *DexGRPCSpec {
	if in == nil {
		return nil
	}
	out := new(DexGRPCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGitHubConnector) DeepCopyInto(out *DexGitHubConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGitHubConnector.
func (in *DexGitHubConnector) DeepCopy() *DexGitHubConnector {
	if in == nil {
		return nil
	}
	out := new(DexGitHubConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexGitHubConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGitHubConnectorList) DeepCopyInto(out *DexGitHubConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexGitHubConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGitHubConnectorList.
func (in *DexGitHubConnectorList) DeepCopy() *DexGitHubConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexGitHubConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexGitHubConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGitHubConnectorSpec) DeepCopyInto(out *DexGitHubConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
	if in.RootCARef != nil {
		in, out := &in.RootCARef, &out.RootCARef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Orgs != nil {
		in, out := &in.Orgs, &out.Orgs
		*out = make([]GitHubOrg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGitHubConnectorSpec.
func (in *DexGitHubConnectorSpec) DeepCopy() *DexGitHubConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexGitHubConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGitHubConnectorStatus) DeepCopyInto(out *DexGitHubConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGitHubConnectorStatus.
func (in *DexGitHubConnectorStatus) DeepCopy() *DexGitHubConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexGitHubConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGitLabConnector) DeepCopyInto(out *DexGitLabConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGitLabConnector.
func (in *DexGitLabConnector) DeepCopy() *DexGitLabConnector {
	if in == nil {
		return nil
	}
	out := new(DexGitLabConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexGitLabConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGitLabConnectorList) DeepCopyInto(out *DexGitLabConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexGitLabConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGitLabConnectorList.
func (in *DexGitLabConnectorList) DeepCopy() *DexGitLabConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexGitLabConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexGitLabConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGitLabConnectorSpec) DeepCopyInto(out *DexGitLabConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGitLabConnectorSpec.
func (in *DexGitLabConnectorSpec) DeepCopy() *DexGitLabConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexGitLabConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGitLabConnectorStatus) DeepCopyInto(out *DexGitLabConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGitLabConnectorStatus.
func (in *DexGitLabConnectorStatus) DeepCopy() *DexGitLabConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexGitLabConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGiteaConnector) DeepCopyInto(out *DexGiteaConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGiteaConnector.
func (in *DexGiteaConnector) DeepCopy() *DexGiteaConnector {
	if in == nil {
		return nil
	}
	out := new(DexGiteaConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexGiteaConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGiteaConnectorList) DeepCopyInto(out *DexGiteaConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexGiteaConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGiteaConnectorList.
func (in *DexGiteaConnectorList) DeepCopy() *DexGiteaConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexGiteaConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexGiteaConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGiteaConnectorSpec) DeepCopyInto(out *DexGiteaConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
	if in.Orgs != nil {
		in, out := &in.Orgs, &out.Orgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RootCARef != nil {
		in, out := &in.RootCARef, &out.RootCARef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGiteaConnectorSpec.
func (in *DexGiteaConnectorSpec) DeepCopy() *DexGiteaConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexGiteaConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGiteaConnectorStatus) DeepCopyInto(out *DexGiteaConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGiteaConnectorStatus.
func (in *DexGiteaConnectorStatus) DeepCopy() *DexGiteaConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexGiteaConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGoogleConnector) DeepCopyInto(out *DexGoogleConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGoogleConnector.
func (in *DexGoogleConnector) DeepCopy() *DexGoogleConnector {
	if in == nil {
		return nil
	}
	out := new(DexGoogleConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexGoogleConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGoogleConnectorList) DeepCopyInto(out *DexGoogleConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexGoogleConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGoogleConnectorList.
func (in *DexGoogleConnectorList) DeepCopy() *DexGoogleConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexGoogleConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexGoogleConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGoogleConnectorSpec) DeepCopyInto(out *DexGoogleConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
	if in.HostedDomains != nil {
		in, out := &in.HostedDomains, &out.HostedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAccountFileRef != nil {
		in, out := &in.ServiceAccountFileRef, &out.ServiceAccountFileRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGoogleConnectorSpec.
func (in *DexGoogleConnectorSpec) DeepCopy() *DexGoogleConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexGoogleConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexGoogleConnectorStatus) DeepCopyInto(out *DexGoogleConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexGoogleConnectorStatus.
func (in *DexGoogleConnectorStatus) DeepCopy() *DexGoogleConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexGoogleConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexInstallation) DeepCopyInto(out *DexInstallation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexInstallation.
func (in *DexInstallation) DeepCopy() *DexInstallation {
	if in == nil {
		return nil
	}
	out := new(DexInstallation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexInstallation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexInstallationList) DeepCopyInto(out *DexInstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexInstallation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexInstallationList.
func (in *DexInstallationList) DeepCopy() *DexInstallationList {
	if in == nil {
		return nil
	}
	out := new(DexInstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexInstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexInstallationSpec) DeepCopyInto(out *DexInstallationSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.Web != nil {
		in, out := &in.Web, &out.Web
		*out = new(DexWebSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CORS != nil {
		in, out := &in.CORS, &out.CORS
		*out = new(DexCORSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GRPC != nil {
		in, out := &in.GRPC, &out.GRPC
		*out = new(DexGRPCSpec)
		**out = **in
	}
	if in.Logger != nil {
		in, out := &in.Logger, &out.Logger
		*out = new(DexLoggerSpec)
		**out = **in
	}
	if in.Expiry != nil {
		in, out := &in.Expiry, &out.Expiry
		*out = new(DexExpirySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OAuth2 != nil {
		in, out := &in.OAuth2, &out.OAuth2
		*out = new(DexOAuth2ConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RolloutRestart != nil {
		in, out := &in.RolloutRestart, &out.RolloutRestart
		*out = new(RolloutRestartSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexInstallationSpec.
func (in *DexInstallationSpec) DeepCopy() *DexInstallationSpec {
	if in == nil {
		return nil
	}
	out := new(DexInstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexInstallationStatus) DeepCopyInto(out *DexInstallationStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexInstallationStatus.
func (in *DexInstallationStatus) DeepCopy() *DexInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(DexInstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexKeystoneConnector) DeepCopyInto(out *DexKeystoneConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexKeystoneConnector.
func (in *DexKeystoneConnector) DeepCopy() *DexKeystoneConnector {
	if in == nil {
		return nil
	}
	out := new(DexKeystoneConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexKeystoneConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexKeystoneConnectorList) DeepCopyInto(out *DexKeystoneConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexKeystoneConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexKeystoneConnectorList.
func (in *DexKeystoneConnectorList) DeepCopy() *DexKeystoneConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexKeystoneConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexKeystoneConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexKeystoneConnectorSpec) DeepCopyInto(out *DexKeystoneConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	if in.AdminPasswordRef != nil {
		in, out := &in.AdminPasswordRef, &out.AdminPasswordRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexKeystoneConnectorSpec.
func (in *DexKeystoneConnectorSpec) DeepCopy() *DexKeystoneConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexKeystoneConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexKeystoneConnectorStatus) DeepCopyInto(out *DexKeystoneConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexKeystoneConnectorStatus.
func (in *DexKeystoneConnectorStatus) DeepCopy() *DexKeystoneConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexKeystoneConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLDAPConnector) DeepCopyInto(out *DexLDAPConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLDAPConnector.
func (in *DexLDAPConnector) DeepCopy() *DexLDAPConnector {
	if in == nil {
		return nil
	}
	out := new(DexLDAPConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexLDAPConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLDAPConnectorList) DeepCopyInto(out *DexLDAPConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexLDAPConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLDAPConnectorList.
func (in *DexLDAPConnectorList) DeepCopy() *DexLDAPConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexLDAPConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexLDAPConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLDAPConnectorSpec) DeepCopyInto(out *DexLDAPConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	if in.RootCARef != nil {
		in, out := &in.RootCARef, &out.RootCARef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.ClientCertRef != nil {
		in, out := &in.ClientCertRef, &out.ClientCertRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.ClientKeyRef != nil {
		in, out := &in.ClientKeyRef, &out.ClientKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.BindPWRef != nil {
		in, out := &in.BindPWRef, &out.BindPWRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	out.UserSearch = in.UserSearch
	if in.GroupSearch != nil {
		in, out := &in.GroupSearch, &out.GroupSearch
		*out = new(LDAPGroupSearch)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLDAPConnectorSpec.
func (in *DexLDAPConnectorSpec) DeepCopy() *DexLDAPConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexLDAPConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLDAPConnectorStatus) DeepCopyInto(out *DexLDAPConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLDAPConnectorStatus.
func (in *DexLDAPConnectorStatus) DeepCopy() *DexLDAPConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexLDAPConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLinkedInConnector) DeepCopyInto(out *DexLinkedInConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLinkedInConnector.
func (in *DexLinkedInConnector) DeepCopy() *DexLinkedInConnector {
	if in == nil {
		return nil
	}
	out := new(DexLinkedInConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexLinkedInConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLinkedInConnectorList) DeepCopyInto(out *DexLinkedInConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexLinkedInConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLinkedInConnectorList.
func (in *DexLinkedInConnectorList) DeepCopy() *DexLinkedInConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexLinkedInConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexLinkedInConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLinkedInConnectorSpec) DeepCopyInto(out *DexLinkedInConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLinkedInConnectorSpec.
func (in *DexLinkedInConnectorSpec) DeepCopy() *DexLinkedInConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexLinkedInConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLinkedInConnectorStatus) DeepCopyInto(out *DexLinkedInConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLinkedInConnectorStatus.
func (in *DexLinkedInConnectorStatus) DeepCopy() *DexLinkedInConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexLinkedInConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLocalConnector) DeepCopyInto(out *DexLocalConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLocalConnector.
func (in *DexLocalConnector) DeepCopy() *DexLocalConnector {
	if in == nil {
		return nil
	}
	out := new(DexLocalConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexLocalConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLocalConnectorList) DeepCopyInto(out *DexLocalConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexLocalConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLocalConnectorList.
func (in *DexLocalConnectorList) DeepCopy() *DexLocalConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexLocalConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexLocalConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLocalConnectorSpec) DeepCopyInto(out *DexLocalConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLocalConnectorSpec.
func (in *DexLocalConnectorSpec) DeepCopy() *DexLocalConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexLocalConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLocalConnectorStatus) DeepCopyInto(out *DexLocalConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLocalConnectorStatus.
func (in *DexLocalConnectorStatus) DeepCopy() *DexLocalConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexLocalConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexLoggerSpec) DeepCopyInto(out *DexLoggerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexLoggerSpec.
func (in *DexLoggerSpec) DeepCopy() *DexLoggerSpec {
	if in == nil {
		return nil
	}
	out := new(DexLoggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexMicrosoftConnector) DeepCopyInto(out *DexMicrosoftConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexMicrosoftConnector.
func (in *DexMicrosoftConnector) DeepCopy() *DexMicrosoftConnector {
	if in == nil {
		return nil
	}
	out := new(DexMicrosoftConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexMicrosoftConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexMicrosoftConnectorList) DeepCopyInto(out *DexMicrosoftConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexMicrosoftConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexMicrosoftConnectorList.
func (in *DexMicrosoftConnectorList) DeepCopy() *DexMicrosoftConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexMicrosoftConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexMicrosoftConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexMicrosoftConnectorSpec) DeepCopyInto(out *DexMicrosoftConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexMicrosoftConnectorSpec.
func (in *DexMicrosoftConnectorSpec) DeepCopy() *DexMicrosoftConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexMicrosoftConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexMicrosoftConnectorStatus) DeepCopyInto(out *DexMicrosoftConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexMicrosoftConnectorStatus.
func (in *DexMicrosoftConnectorStatus) DeepCopy() *DexMicrosoftConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexMicrosoftConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexMySQLStorageSpec) DeepCopyInto(out *DexMySQLStorageSpec) {
	*out = *in
	if in.DSNRef != nil {
		in, out := &in.DSNRef, &out.DSNRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.MaxOpenConns != nil {
		in, out := &in.MaxOpenConns, &out.MaxOpenConns
		*out = new(int)
		**out = **in
	}
	if in.MaxIdleConns != nil {
		in, out := &in.MaxIdleConns, &out.MaxIdleConns
		*out = new(int)
		**out = **in
	}
	if in.ConnMaxLifetime != nil {
		in, out := &in.ConnMaxLifetime, &out.ConnMaxLifetime
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexMySQLStorageSpec.
func (in *DexMySQLStorageSpec) DeepCopy() *DexMySQLStorageSpec {
	if in == nil {
		return nil
	}
	out := new(DexMySQLStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOAuth2ConfigSpec) DeepCopyInto(out *DexOAuth2ConfigSpec) {
	*out = *in
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOAuth2ConfigSpec.
func (in *DexOAuth2ConfigSpec) DeepCopy() *DexOAuth2ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DexOAuth2ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOAuth2Connector) DeepCopyInto(out *DexOAuth2Connector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOAuth2Connector.
func (in *DexOAuth2Connector) DeepCopy() *DexOAuth2Connector {
	if in == nil {
		return nil
	}
	out := new(DexOAuth2Connector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexOAuth2Connector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOAuth2ConnectorList) DeepCopyInto(out *DexOAuth2ConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexOAuth2Connector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOAuth2ConnectorList.
func (in *DexOAuth2ConnectorList) DeepCopy() *DexOAuth2ConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexOAuth2ConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexOAuth2ConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOAuth2ConnectorSpec) DeepCopyInto(out *DexOAuth2ConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RootCARef != nil {
		in, out := &in.RootCARef, &out.RootCARef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.ClaimMapping != nil {
		in, out := &in.ClaimMapping, &out.ClaimMapping
		*out = new(OAuth2ClaimMapping)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOAuth2ConnectorSpec.
func (in *DexOAuth2ConnectorSpec) DeepCopy() *DexOAuth2ConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexOAuth2ConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOAuth2ConnectorStatus) DeepCopyInto(out *DexOAuth2ConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOAuth2ConnectorStatus.
func (in *DexOAuth2ConnectorStatus) DeepCopy() *DexOAuth2ConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexOAuth2ConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOIDCConnector) DeepCopyInto(out *DexOIDCConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOIDCConnector.
func (in *DexOIDCConnector) DeepCopy() *DexOIDCConnector {
	if in == nil {
		return nil
	}
	out := new(DexOIDCConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexOIDCConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOIDCConnectorList) DeepCopyInto(out *DexOIDCConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexOIDCConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOIDCConnectorList.
func (in *DexOIDCConnectorList) DeepCopy() *DexOIDCConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexOIDCConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexOIDCConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOIDCConnectorSpec) DeepCopyInto(out *DexOIDCConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClaimMapping != nil {
		in, out := &in.ClaimMapping, &out.ClaimMapping
		*out = new(OIDCClaimMapping)
		**out = **in
	}
	if in.HostedDomains != nil {
		in, out := &in.HostedDomains, &out.HostedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ACRValues != nil {
		in, out := &in.ACRValues, &out.ACRValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RootCARef != nil {
		in, out := &in.RootCARef, &out.RootCARef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOIDCConnectorSpec.
func (in *DexOIDCConnectorSpec) DeepCopy() *DexOIDCConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexOIDCConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOIDCConnectorStatus) DeepCopyInto(out *DexOIDCConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOIDCConnectorStatus.
func (in *DexOIDCConnectorStatus) DeepCopy() *DexOIDCConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexOIDCConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOpenShiftConnector) DeepCopyInto(out *DexOpenShiftConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOpenShiftConnector.
func (in *DexOpenShiftConnector) DeepCopy() *DexOpenShiftConnector {
	if in == nil {
		return nil
	}
	out := new(DexOpenShiftConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexOpenShiftConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOpenShiftConnectorList) DeepCopyInto(out *DexOpenShiftConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexOpenShiftConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOpenShiftConnectorList.
func (in *DexOpenShiftConnectorList) DeepCopy() *DexOpenShiftConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexOpenShiftConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexOpenShiftConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOpenShiftConnectorSpec) DeepCopyInto(out *DexOpenShiftConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.ClientIDRef = in.ClientIDRef
	out.ClientSecretRef = in.ClientSecretRef
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RootCARef != nil {
		in, out := &in.RootCARef, &out.RootCARef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOpenShiftConnectorSpec.
func (in *DexOpenShiftConnectorSpec) DeepCopy() *DexOpenShiftConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexOpenShiftConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexOpenShiftConnectorStatus) DeepCopyInto(out *DexOpenShiftConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexOpenShiftConnectorStatus.
func (in *DexOpenShiftConnectorStatus) DeepCopy() *DexOpenShiftConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexOpenShiftConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexPostgresSSLSpec) DeepCopyInto(out *DexPostgresSSLSpec) {
	*out = *in
	if in.CARef != nil {
		in, out := &in.CARef, &out.CARef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.CertRef != nil {
		in, out := &in.CertRef, &out.CertRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.KeyRef != nil {
		in, out := &in.KeyRef, &out.KeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexPostgresSSLSpec.
func (in *DexPostgresSSLSpec) DeepCopy() *DexPostgresSSLSpec {
	if in == nil {
		return nil
	}
	out := new(DexPostgresSSLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexPostgresStorageSpec) DeepCopyInto(out *DexPostgresStorageSpec) {
	*out = *in
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(DexPostgresSSLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionTimeout != nil {
		in, out := &in.ConnectionTimeout, &out.ConnectionTimeout
		*out = new(int)
		**out = **in
	}
	if in.MaxOpenConns != nil {
		in, out := &in.MaxOpenConns, &out.MaxOpenConns
		*out = new(int)
		**out = **in
	}
	if in.MaxIdleConns != nil {
		in, out := &in.MaxIdleConns, &out.MaxIdleConns
		*out = new(int)
		**out = **in
	}
	if in.ConnMaxLifetime != nil {
		in, out := &in.ConnMaxLifetime, &out.ConnMaxLifetime
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexPostgresStorageSpec.
func (in *DexPostgresStorageSpec) DeepCopy() *DexPostgresStorageSpec {
	if in == nil {
		return nil
	}
	out := new(DexPostgresStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexRefreshTokenExpirySpec) DeepCopyInto(out *DexRefreshTokenExpirySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexRefreshTokenExpirySpec.
func (in *DexRefreshTokenExpirySpec) DeepCopy() *DexRefreshTokenExpirySpec {
	if in == nil {
		return nil
	}
	out := new(DexRefreshTokenExpirySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexSAMLConnector) DeepCopyInto(out *DexSAMLConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexSAMLConnector.
func (in *DexSAMLConnector) DeepCopy() *DexSAMLConnector {
	if in == nil {
		return nil
	}
	out := new(DexSAMLConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexSAMLConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexSAMLConnectorList) DeepCopyInto(out *DexSAMLConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexSAMLConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexSAMLConnectorList.
func (in *DexSAMLConnectorList) DeepCopy() *DexSAMLConnectorList {
	if in == nil {
		return nil
	}
	out := new(DexSAMLConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexSAMLConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexSAMLConnectorSpec) DeepCopyInto(out *DexSAMLConnectorSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	if in.CARef != nil {
		in, out := &in.CARef, &out.CARef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.CABundleRef != nil {
		in, out := &in.CABundleRef, &out.CABundleRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.AllowedGroups != nil {
		in, out := &in.AllowedGroups, &out.AllowedGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexSAMLConnectorSpec.
func (in *DexSAMLConnectorSpec) DeepCopy() *DexSAMLConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(DexSAMLConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexSAMLConnectorStatus) DeepCopyInto(out *DexSAMLConnectorStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexSAMLConnectorStatus.
func (in *DexSAMLConnectorStatus) DeepCopy() *DexSAMLConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(DexSAMLConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexSQLite3StorageSpec) DeepCopyInto(out *DexSQLite3StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexSQLite3StorageSpec.
func (in *DexSQLite3StorageSpec) DeepCopy() *DexSQLite3StorageSpec {
	if in == nil {
		return nil
	}
	out := new(DexSQLite3StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexStaticClient) DeepCopyInto(out *DexStaticClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexStaticClient.
func (in *DexStaticClient) DeepCopy() *DexStaticClient {
	if in == nil {
		return nil
	}
	out := new(DexStaticClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexStaticClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexStaticClientList) DeepCopyInto(out *DexStaticClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexStaticClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexStaticClientList.
func (in *DexStaticClientList) DeepCopy() *DexStaticClientList {
	if in == nil {
		return nil
	}
	out := new(DexStaticClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexStaticClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexStaticClientSpec) DeepCopyInto(out *DexStaticClientSpec) {
	*out = *in
	out.InstallationRef = in.InstallationRef
	out.SecretRef = in.SecretRef
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedScopes != nil {
		in, out := &in.AllowedScopes, &out.AllowedScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TrustedPeers != nil {
		in, out := &in.TrustedPeers, &out.TrustedPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexStaticClientSpec.
func (in *DexStaticClientSpec) DeepCopy() *DexStaticClientSpec {
	if in == nil {
		return nil
	}
	out := new(DexStaticClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexStaticClientStatus) DeepCopyInto(out *DexStaticClientStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexStaticClientStatus.
func (in *DexStaticClientStatus) DeepCopy() *DexStaticClientStatus {
	if in == nil {
		return nil
	}
	out := new(DexStaticClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexStorageSpec) DeepCopyInto(out *DexStorageSpec) {
	*out = *in
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(DexPostgresStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SQLite3 != nil {
		in, out := &in.SQLite3, &out.SQLite3
		*out = new(DexSQLite3StorageSpec)
		**out = **in
	}
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(DexEtcdStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(DexMySQLStorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexStorageSpec.
func (in *DexStorageSpec) DeepCopy() *DexStorageSpec {
	if in == nil {
		return nil
	}
	out := new(DexStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexWebSpec) DeepCopyInto(out *DexWebSpec) {
	*out = *in
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexWebSpec.
func (in *DexWebSpec) DeepCopy() *DexWebSpec {
	if in == nil {
		return nil
	}
	out := new(DexWebSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubOrg) DeepCopyInto(out *GitHubOrg) {
	*out = *in
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubOrg.
func (in *GitHubOrg) DeepCopy() *GitHubOrg {
	if in == nil {
		return nil
	}
	out := new(GitHubOrg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationRef) DeepCopyInto(out *InstallationRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationRef.
func (in *InstallationRef) DeepCopy() *InstallationRef {
	if in == nil {
		return nil
	}
	out := new(InstallationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPGroupSearch) DeepCopyInto(out *LDAPGroupSearch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPGroupSearch.
func (in *LDAPGroupSearch) DeepCopy() *LDAPGroupSearch {
	if in == nil {
		return nil
	}
	out := new(LDAPGroupSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPUserSearch) DeepCopyInto(out *LDAPUserSearch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPUserSearch.
func (in *LDAPUserSearch) DeepCopy() *LDAPUserSearch {
	if in == nil {
		return nil
	}
	out := new(LDAPUserSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ClaimMapping) DeepCopyInto(out *OAuth2ClaimMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ClaimMapping.
func (in *OAuth2ClaimMapping) DeepCopy() *OAuth2ClaimMapping {
	if in == nil {
		return nil
	}
	out := new(OAuth2ClaimMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCClaimMapping) DeepCopyInto(out *OIDCClaimMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCClaimMapping.
func (in *OIDCClaimMapping) DeepCopy() *OIDCClaimMapping {
	if in == nil {
		return nil
	}
	out := new(OIDCClaimMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutRestartSpec) DeepCopyInto(out *RolloutRestartSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutRestartSpec.
func (in *RolloutRestartSpec) DeepCopy() *RolloutRestartSpec {
	if in == nil {
		return nil
	}
	out := new(RolloutRestartSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticClientSecretRef) DeepCopyInto(out *StaticClientSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticClientSecretRef.
func (in *StaticClientSecretRef) DeepCopy() *StaticClientSecretRef {
	if in == nil {
		return nil
	}
	out := new(StaticClientSecretRef)
	in.DeepCopyInto(out)
	return out
}
