apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dex-operator
  name: dex-operator-controller-manager
  namespace: dex-operator-system
